# name: Build
# on:
#   schedule:
#     - cron: "0 0 * * *"
# jobs:
#   build:
#     # ...
#   keepalive:
#     if: github.event_name == 'schedule'
#     runs-on: ubuntu-latest
#     permissions:
#       actions: write
#     steps:
#       - uses: liskin/gh-workflow-keepalive@v1
