# name: Build
# on:
#   schedule:
#     - cron: "0 0 * * *"
# jobs:
#   build:
#     # ...
#     - name: Build & Deploy Worker
#       uses: cloudflare/wrangler-action@v3
#       with:
#         wranglerVersion: "latest"  <-- HERE
#         accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
#         apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
#   keepalive:
#     if: github.event_name == 'schedule'
#     runs-on: ubuntu-latest
#     permissions:
#       actions: write
#     steps:
#       - uses: liskin/gh-workflow-keepalive@v1
